title: Christian B채uerlein
email: fabrik42@gmail.com
baseurl: ""
url: "https://christianbaeuerlein.com"

description: >
  Hi! My name is Christian B채uerlein,
  a software developer living in Frankfurt, Germany.

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      image: "/assets/social-link-image_TODO.png"

exclude:
  - README.org
  - slides_backup

# Social / SEO settings

logo: "/assets/social-link-logo.jpg"

google_site_verification: "ok3_egP8JYWNjujovfiEWeCPFMnI9c49PYcBlAREkr4"

author:
  name: Christian B채uerlein
  twitter: fabrik42
  url: https://christianbaeuerlein.com/
  picture: /assets/social-link-author_TODO.png

social:
  name: Christian B채uerlein
  links:
    - https://twitter.com/fabrik42
    - https://mastodon.social/@fabrik42
    - https://www.linkedin.com/in/christian-baeuerlein
    - https://github.com/fabrik42
