# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Christian Bäuerlein
email: fabrik42@gmail.com
webmaster_verification: 'ok3_egP8JYWNjujovfiEWeCPFMnI9c49PYcBlAREkr4'
description: >
  Hi! My name is Christian Bäuerlein,
  a software developer living in Frankfurt, Germany.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://christianbaeuerlein.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fabrik42
github_username: fabrik42
mastodon_username: fabrik42

# Build settings
markdown: kramdown

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
exclude:
  - README.org
  - slides_backup
